# Implementacja kodu PBIL

In [1]:
import numpy as np
import random
from typing import List

CHROMOSOME_LEN = 20
POPULATION_LEN = 3
ITERATION_NUM = 10000

def binary_random(p):
    return 1 if random.random() <= p else 0

def random_individual(p: List[float]) -> np.ndarray:
    return np.array([binary_random(pi) for pi in p])

def random_population(p: List[float], N: int = POPULATION_LEN) -> np.ndarray:
    return np.array([random_individual(p) for _ in range(N)])

def population_evaluation(P: List[List[int]], F):
    return np.array([F(x) for x in P])

def population_based_incremental_learning(F, N: int, O1, O2, O3):
    pro_vector = np.array([0.5 for _ in range(N)])                      # Initial Probabilty Vector
    ran_population = random_population(pro_vector, POPULATION_LEN)      # Initial Random Population 
    fitness = population_evaluation(ran_population, F)                  # 
    for _ in range(ITERATION_NUM):
        x = ran_population[np.argmax(fitness)]

        for i in range(N):
            pro_vector[i] = pro_vector[i] * (1 - O1) + (x[i] * O1)

        for i in range(N):
            if random.random() <= O2:
                pro_vector[i] = pro_vector[i] * (1 - O3) + O3 * binary_random(0.5)

        ran_population = random_population(pro_vector, POPULATION_LEN)
        fitness = population_evaluation(ran_population, F)

    return ran_population[np.argmax(fitness)]


In [2]:
def one_max(seq: List[int]) -> int:
    return np.sum(seq) 

def deceptive_one_max(seq: List[int]) -> int:
    res = np.sum(seq)
    n = len(seq)
    if res == n:
        return n  
    else:
        return n - res - 1

def k_deceptive_one_max(seq: List[int], k: int = 4) -> int:
    n = len(seq)
    assert n % k == 0, "Sequence length must be divisible by k"
    
    total = 0
    for i in range(0, n, k):
        block = seq[i:i+k]
        u = np.sum(block)
        if u == k:
            total += k  # global optimum for block
        else:
            total += k - 1 - u  # deceptive trap
    return total
    

print(population_based_incremental_learning(one_max, CHROMOSOME_LEN, 0.1, 0.1, 0.1))
print(population_based_incremental_learning(deceptive_one_max, CHROMOSOME_LEN, 0.1, 0.1, 0.1))
print(population_based_incremental_learning(k_deceptive_one_max, CHROMOSOME_LEN, 0.1, 0.1, 0.1))

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
[0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1]


<div align="center">

## Badanie OneMax

</div>

In [3]:
print("Rozpoczynam testy dla OneMax\n")

for i in range(1, 11):
    O1 = random.random()
    O2 = random.random()
    O3 = random.random()
    chromosome_size = random.randint(10, 50)

    print(f"Test numer: {i}\nFunction: one_max\nChromosome size: {chromosome_size}\nO1: {O1}\nO2: {O2}\nO3: {O3}n\nBest individual: ", end='')

    print(population_based_incremental_learning(one_max, chromosome_size, O1, O2, O3), end="\n\n")

Rozpoczynam testy dla OneMax

Test numer: 1
Function: one_max
Chromosome size: 35
O1: 0.7630888253490438
O2: 0.08135847111434136
O3: 0.026144825227750634n
Best individual: [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Test numer: 2
Function: one_max
Chromosome size: 36
O1: 0.23087714446414787
O2: 0.7212340185435872
O3: 0.9541874625790971n
Best individual: [1 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 0 1 0 1 1 0 0 0 1 1 0 0 0 1 1 0 0 1 1]

Test numer: 3
Function: one_max
Chromosome size: 36
O1: 0.6568189550634346
O2: 0.7627355610643873
O3: 0.03248783312458503n
Best individual: [1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]

Test numer: 4
Function: one_max
Chromosome size: 42
O1: 0.09453245366973839
O2: 0.5416352415687216
O3: 0.9671609532460099n
Best individual: [0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 1 1 0 1 0 0 0 0 0 0 1 1 1 1 0 1 0 1 1 1 1 1
 0 0 0 1 1]

Test numer: 5
Function: one_max
Chromosome size: 15
O1: 0.21100351920268512
O2: 0.860830412248462

<div align="center">

## Badanie Deceptive OneMax

</div>

In [4]:
print("Rozpoczynam testy dla Deceptive OneMax\n")

for i in range(1, 11):
    O1 = random.random()
    O2 = random.random()
    O3 = random.random()
    chromosome_size = random.randint(10, 50)

    print(f"Test numer: {i}\nFunction: one_max\nChromosome size: {chromosome_size}\nO1: {O1}\nO2: {O2}\nO3: {O3}n\nBest individual: ", end='')

    print(population_based_incremental_learning(deceptive_one_max, chromosome_size, O1, O2, O3), end="\n\n")

Rozpoczynam testy dla Deceptive OneMax

Test numer: 1
Function: one_max
Chromosome size: 33
O1: 0.9464489306361585
O2: 0.9398181887210015
O3: 0.16122695087837147n
Best individual: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 1 1 1 0 0 0]

Test numer: 2
Function: one_max
Chromosome size: 16
O1: 0.5344273954801065
O2: 0.5268930881749572
O3: 0.6668341153990582n
Best individual: [1 0 1 0 1 0 1 0 1 0 0 1 1 0 0 0]

Test numer: 3
Function: one_max
Chromosome size: 41
O1: 0.5633027827549838
O2: 0.8868653251797809
O3: 0.6783531443579597n
Best individual: [0 0 1 1 0 1 1 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0
 0 0 1 0]

Test numer: 4
Function: one_max
Chromosome size: 43
O1: 0.3758912284114564
O2: 0.438355253433349
O3: 0.5965668690218059n
Best individual: [0 0 1 0 0 1 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 0 1 0 0 1 0 1 1 1 0 1 1 1 1 0
 1 0 1 0 0 0]

Test numer: 5
Function: one_max
Chromosome size: 14
O1: 0.4045103344226336
O2: 0.539505632854896
O3: 0.7924850860343943n
Bes

<div align="center"> 

## Badanie K-Deceptive OneMax

</div>

In [5]:
print("Rozpoczynam testy dla K-Deceptive OneMax\n")

for i in range(1, 11):
    O1 = random.random()
    O2 = random.random()
    O3 = random.random()

    print(f"Test numer: {i}\nFunction: one_max\nChromosome size: {CHROMOSOME_LEN}\nO1: {O1}\nO2: {O2}\nO3: {O3}n\nBest individual: ", end='')

    print(population_based_incremental_learning(k_deceptive_one_max, CHROMOSOME_LEN, O1, O2, O3), end="\n\n")

Rozpoczynam testy dla K-Deceptive OneMax

Test numer: 1
Function: one_max
Chromosome size: 20
O1: 0.05602239152218502
O2: 0.15180287657150293
O3: 0.6233949084710987n
Best individual: [0 0 0 1 0 0 1 0 1 1 1 1 0 0 1 1 0 1 1 0]

Test numer: 2
Function: one_max
Chromosome size: 20
O1: 0.7800820986134542
O2: 0.6490665456546739
O3: 0.6880497856156295n
Best individual: [1 0 0 1 0 0 0 1 1 1 1 0 0 1 0 0 0 1 0 0]

Test numer: 3
Function: one_max
Chromosome size: 20
O1: 0.9887343070840398
O2: 0.41751855595755105
O3: 0.3180091740463693n
Best individual: [0 1 0 0 1 1 1 1 0 0 1 0 1 0 0 1 0 0 0 0]

Test numer: 4
Function: one_max
Chromosome size: 20
O1: 0.5717427361713882
O2: 0.9454616712847185
O3: 0.5572110882813831n
Best individual: [1 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 1 1]

Test numer: 5
Function: one_max
Chromosome size: 20
O1: 0.8280651015223689
O2: 0.5657303399437432
O3: 0.14850128493951575n
Best individual: [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]

Test numer: 6
Function: one_max
Chromosome s